const avatarMap = {
    'admin1.jpg': require('../assets/images/avatars/admin1.jpg'),
    'brown.jpg': require('../assets/images/avatars/brown.jpg'),
    'jones.jpg': require('../assets/images/avatars/jones.jpg'),
    'smith.jpg': require('../assets/images/avatars/smith.jpg'),
    'student1.jpg': require('../assets/images/avatars/student1.jpg'),
    'student2.jpg': require('../assets/images/avatars/student2.jpg'),
    'student3.jpg': require('../assets/images/avatars/student3.jpg'),
    'student4.jpg': require('../assets/images/avatars/student4.jpg'),
    'student5.jpg': require('../assets/images/avatars/student5.jpg'),
    'student6.jpg': require('../assets/images/avatars/student6.jpg'),
    'student7.jpg': require('../assets/images/avatars/student7.jpg'),
    'student8.jpg': require('../assets/images/avatars/student8.jpg'),
    'student9.jpg': require('../assets/images/avatars/student9.jpg'),
    'student10.jpg': require('../assets/images/avatars/student10.jpg'),
    'student11.jpg': require('../assets/images/avatars/student11.jpg'),
    'student12.jpg': require('../assets/images/avatars/student12.jpg'),
    'student13.jpg': require('../assets/images/avatars/student13.jpg'),
    'student14.jpg': require('../assets/images/avatars/student14.jpg'),
    'student15.jpg': require('../assets/images/avatars/student15.jpg'),
    'student16.jpg': require('../assets/images/avatars/student16.jpg'),
    'student17.jpg': require('../assets/images/avatars/student17.jpg'),
    'student18.jpg': require('../assets/images/avatars/student18.jpg'),
    'student19.jpg': require('../assets/images/avatars/student19.jpg'),
    'student20.jpg': require('../assets/images/avatars/student20.jpg'),
    'student21.jpg': require('../assets/images/avatars/student21.jpg'),
    'student22.jpg': require('../assets/images/avatars/student22.jpg'),
    'student23.jpg': require('../assets/images/avatars/student23.jpg'),
    'student24.jpg': require('../assets/images/avatars/student24.jpg'),
    'student25.jpg': require('../assets/images/avatars/student25.jpg'),
    'student26.jpg': require('../assets/images/avatars/student26.jpg'),
    'student27.jpg': require('../assets/images/avatars/student27.jpg'),
    'student28.jpg': require('../assets/images/avatars/student28.jpg'),
    'student29.jpg': require('../assets/images/avatars/student29.jpg'),
    'student30.jpg': require('../assets/images/avatars/student30.jpg'),
    'admin1.jpg': require('../assets/images/avatars/admin1.jpg'),
    'brown.jpg': require('../assets/images/avatars/brown.jpg'),
    'jones.jpg': require('../assets/images/avatars/jones.jpg'),
    'smith.jpg': require('../assets/images/avatars/smith.jpg'),
  };
  
  export default avatarMap;